development:
  adapter: mysql2
  encoding: utf8
  database: shoppe_example
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: shoppe_example_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
